# Docker Compose for Pneumonia Detection System
# docker/docker-compose.yml

version: '3.8'

services:
  pneumonia-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: pneumonia-detection-api:latest
    container_name: pneumonia-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ../model:/app/model
    restart: unless-stopped
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 4G
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - MODEL_PATH=/app/model/model.h5
      - CONFIG_PATH=/app/model/model_config.json
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - PORT=8000